test: try with single ping
dns

diff --git a/src/kindsealion/templates/dns.sh.j2 b/src/kindsealion/templates/dns.sh.j2
--- a/src/kindsealion/templates/dns.sh.j2
+++ b/src/kindsealion/templates/dns.sh.j2
@@ -4,29 +4,22 @@ set -e
 set -u
 set -x
 
-
 start_time=$(date +%s)
-end_time=$((start_time + 30))
-consecutive_successes=0
+timeout=60
 
-while [ $consecutive_successes -lt 3 ]; do
- if ping -c 1 google.com &> /dev/null; then
-   ((consecutive_successes++))
- else
-   consecutive_successes=0
- fi
+while true; do
+    if ping -c 1 google.com &> /dev/null; then
+        echo "Ping successful. Exiting with status 0."
+        exit 0
+    fi
 
- current_time=$(date +%s)
- time_remaining=$((end_time - current_time))
+    current_time=$(date +%s)
+    elapsed_time=$((current_time - start_time))
 
- if [ $time_remaining -le 0 ]; then
-   echo "Time limit of 30 seconds reached without achieving 3 consecutive successes."
-   exit 1
- fi
+    if [ $elapsed_time -ge $timeout ]; then
+        echo "Ping failed for 1 minute. Exiting with status 1."
+        exit 1
+    fi
 
- echo "Time remaining: $time_remaining seconds"
- sleep 1
+    sleep 1
 done
-
-echo "3 consecutive successful pings to google.com achieved within 30 seconds."
-exit 0
